version: '3.2' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: angular-app # specify the directory of the Dockerfile
  ports:
  - "4200:4200" # specify port mapping
  volumes:
  - ./angular-app:/usr/src/app
 
 express: # name of the second service
  build: node-server # specify the directory of the Dockerfile
  ports:
  - "3000:3000" #specify ports mapping
  links:
  - mongodb # link this service to the database service
 
 mongodb: # name of the third service
  image: mongo # specify image to build container from
  ports:
  - "27017:27017" # specify port forwarding
  volumes:
  - ./mongo-database:/data/db